good_morningdlg =[
            "Good Morning Boss! Hope you have an amazing day ahead!",
            "Good Morning! Another beautiful day to achieve greatness!",
            "Rise and shine, Boss! The world awaits your brilliance!",
            "Good Morning! Time to make the most of this day!",
            "Top of the morning to you, Boss!",
            "Good Morning! Let's crush today's goals!",
            "Morning, Boss! Every sunrise brings new opportunities!",
            "Good Morning! I'm ready to assist you in every way!",
            "Good Morning! Wishing you a day full of productivity!",
            "Morning! Don't forget to smile and conquer the day!",
            "Good Morning! Let's turn today's dreams into reality!",
            "Morning, Boss! It's time to get things done!",
            "Good Morning! May today be full of success!",
            "Good Morning! The early bird gets the worm!",
            "Good Morning! Let's make today the best one yet!",
            "Morning, Boss! I’m all set to help you achieve your goals!",
            "Good Morning! I hope today is as amazing as you are!",
            "Good Morning! Time to rise, grind, and shine!",
            "Good Morning! Today is another chance to shine!",
            "Good Morning! Let's make today count!",
            "Good Morning! May your day be as bright as your ideas!",
            "Morning, Boss! Here's to a day full of wins!",
            "Good Morning! Ready to create something awesome today?",
            "Good Morning! Another day to be productive and proud!",
            "Good Morning! Time to shine like the morning sun!",
            "Good Morning! Let's make magic happen today!",
            "Morning! A fresh start for new opportunities!",
            "Good Morning! May your coffee be strong and your day productive!",
            "Good Morning! Time to get started on something amazing!",
            "Good Morning! Here's to a day of achievements and joy!",
            "Good Morning! Ready to tackle today's challenges?",
            "Morning! I'm all set to assist you in making today a success!",
            "Good Morning! Let’s make today your best one yet!",
            "Good Morning, Boss! I hope today is full of accomplishments!",
            "Good Morning! Let's seize the day together!",
            "Morning, Boss! Time to rise and dominate the day!",
            "Good Morning! Wishing you a day filled with creativity!",
            "Morning! The world is yours today, let’s get started!",
            "Good Morning! Let's turn today's efforts into tomorrow's success!",
            "Morning! Every great day starts with a good morning!",
            "Good Morning! Here's to a productive and positive day!",
            "Morning, Boss! Another day, another opportunity!",
            "Good Morning! Time to make your mark on the world today!",
            "Good Morning! May your day be as inspiring as your vision!",
            "Good Morning! The day is yours to conquer!",
            "Good Morning, Boss! Let's make today legendary!",
            "Good Morning! Every sunrise brings new possibilities!",
            "Morning! Time to turn today's challenges into opportunities!",
            "Good Morning! Let's set the tone for a fantastic day ahead!"
]

good_afternoondlg = [
            "Good Afternoon, Boss! Hope your day is going well!",
            "Good Afternoon! Let's make the rest of the day productive!",
            "Good Afternoon, Boss! Ready to finish the day strong?",
            "Good Afternoon! Hope your day is as bright as the sun!",
            "Afternoon, Boss! How can I assist you this afternoon?",
            "Good Afternoon! Ready for the second half of the day?",
            "Good Afternoon! I’m here to help with anything you need!",
            "Good Afternoon, Boss! Time to wrap up the day in style!",
            "Good Afternoon! How can I make this afternoon easier for you?",
            "Afternoon, Boss! Let’s make the most of the remaining hours!",
            "Good Afternoon! Hope your day has been fantastic so far!",
            "Good Afternoon, Boss! Let's conquer the rest of the day!",
            "Afternoon! How about we get those tasks completed?",
            "Good Afternoon! I'm here to keep the momentum going!",
            "Good Afternoon, Boss! Let's keep pushing forward!",
            "Afternoon! The day isn’t over yet, let’s make it count!",
            "Good Afternoon! Wishing you a smooth and productive rest of the day!",
            "Good Afternoon! How's everything going so far?",
            "Good Afternoon, Boss! Let's finish today on a high note!",
            "Afternoon, Boss! Ready to continue your winning streak?",
            "Good Afternoon! Hope the morning was productive. Let's keep it up!",
            "Good Afternoon! What can I do to help you finish the day strong?",
            "Good Afternoon! How can we make the rest of your day successful?",
            "Good Afternoon, Boss! Let’s keep the energy up for the rest of the day!",
            "Afternoon! I'm ready to assist you with anything you need!",
            "Good Afternoon! Let’s turn the rest of the day into something special!",
            "Good Afternoon, Boss! Time to wrap up those goals!",
            "Afternoon, Boss! What's next on the agenda?",
            "Good Afternoon! Let's make sure this afternoon is productive!",
            "Good Afternoon, Boss! How has your day been so far?",
            "Good Afternoon! Anything I can do to make the rest of your day easier?",
            "Good Afternoon! Time to finish the day with a bang!",
            "Good Afternoon, Boss! Ready to tackle the afternoon tasks?",
            "Afternoon! What can we accomplish together this afternoon?",
            "Good Afternoon! I hope your afternoon is going smoothly!",
            "Good Afternoon! We’ve got this, Boss. Let’s finish strong!",
            "Good Afternoon! I'm here to ensure a productive afternoon!",
            "Good Afternoon, Boss! How about we take care of the remaining tasks?",
            "Afternoon! Let’s get things wrapped up for the day!",
            "Good Afternoon! Hope your day has been going as planned!",
            "Good Afternoon, Boss! What can I assist you with this afternoon?",
            "Good Afternoon! How’s everything going? Ready to finish the day strong?",
            "Afternoon! Here’s to making the most of the rest of your day!",
            "Good Afternoon, Boss! Let's make sure you finish the day with success!",
            "Good Afternoon! How about we close out the day on a positive note?",
            "Afternoon, Boss! What’s the next big task?",
            "Good Afternoon! Time to wrap things up and end the day on a high!",
            "Good Afternoon, Boss! Hope your day is shaping up well!",
            "Good Afternoon! What can I do to assist you this afternoon?",
            "Afternoon! Hope you're having a fantastic day so far!",
            "Good Afternoon, Boss! The day’s not over, so let's keep going strong!"
]

good_eveningdlg = [
            "Good Evening, Boss! Hope you had a productive day!",
            "Good Evening! How was your day, Boss?",
            "Good Evening, Boss! Let’s wind down and relax.",
            "Evening, Boss! Time to wrap up the day!",
            "Good Evening! What can I assist you with tonight?",
            "Good Evening, Boss! Ready to call it a day or keep going?",
            "Evening, Boss! Hope your day went well!",
            "Good Evening! How can I make the rest of your evening better?",
            "Good Evening, Boss! Let’s finish the day on a high note!",
            "Good Evening! Time to relax and enjoy your evening!",
            "Evening, Boss! Anything left on the agenda for today?",
            "Good Evening, Boss! Let’s unwind and reflect on the day.",
            "Evening, Boss! I’m here if you need help wrapping up!",
            "Good Evening! Hope you’re feeling accomplished today!",
            "Good Evening, Boss! How was your day? Ready for a peaceful night?",
            "Evening! Time to wind down and relax after a long day.",
            "Good Evening, Boss! Ready for a calm and peaceful night?",
            "Good Evening! Let’s reflect on today’s achievements, Boss.",
            "Good Evening, Boss! I’m here to help you close out the day.",
            "Evening, Boss! It’s time to prepare for a restful night!",
            "Good Evening! Hope your evening is as relaxing as you deserve.",
            "Good Evening, Boss! Ready to wrap up the final tasks for today?",
            "Good Evening! How can I make your evening more relaxing, Boss?",
            "Evening, Boss! You’ve earned some time to relax tonight!",
            "Good Evening! It’s the perfect time to recharge for tomorrow!",
            "Good Evening, Boss! Let's get those last-minute tasks done.",
            "Good Evening! The night is young, anything I can assist with?",
            "Good Evening, Boss! Time to wind down, but I'm always here for you.",
            "Good Evening! Let’s close out today with success and peace!",
            "Evening, Boss! I hope you had a productive day!",
            "Good Evening, Boss! Let’s make the most of tonight.",
            "Good Evening! How can I assist you as you wind down?",
            "Good Evening, Boss! It’s time to relax and enjoy your evening!",
            "Evening! I hope you’re feeling relaxed and at ease, Boss.",
            "Good Evening! Here’s to a restful night ahead!",
            "Good Evening, Boss! Time to close out the day and recharge.",
            "Evening, Boss! Anything I can help with before the night sets in?",
            "Good Evening! Let’s wrap up the last few things for today.",
            "Good Evening, Boss! I hope you had a fantastic day!",
            "Good Evening! How can I make your evening more peaceful, Boss?",
            "Evening, Boss! Let’s wind down and prepare for tomorrow!",
            "Good Evening, Boss! What’s the plan for tonight?",
            "Good Evening! I’m here to help you settle in for the night.",
            "Good Evening, Boss! Let’s wrap up the day with a sense of accomplishment.",
            "Evening, Boss! It’s time to relax and enjoy some downtime.",
            "Good Evening! Ready to relax after a busy day?",
            "Good Evening, Boss! Let’s wrap up your tasks and enjoy the night.",
            "Good Evening! I hope the rest of your evening is peaceful and calm.",
            "Evening, Boss! Hope your night is as restful as your day was productive.",
            "Good Evening! Let’s close the day on a positive note, Boss.",
            "Good Evening, Boss! I'm ready to help you relax after a long day."

]

welcome_dlg = [
    "Hi sir!",
    "Hello sir!",
    "Glad to see you again, sir!",
    "Good to see you, sir!",
    "Welcome back, sir!",
    "How can I assist you today, sir?",
    "Nice to have you back, sir!",
    "At your service, sir!",
    "It's a pleasure to see you, sir!",
    "Good day, sir!",
    "What can I do for you today, sir?",
    "Hello again, sir!",
    "Great to see you, sir!",
    "Always a pleasure, sir!",
    "How may I help you, sir?",
    "Good to hear from you, sir!",
    "What’s on the agenda today, sir?",
    "I'm ready for you, sir!",
    "Here to assist you, sir!",
    "How can I be of service, sir?",
    "Good morning, sir!",
    "Good afternoon, sir!",
    "Good evening, sir!",
    "How’s your day going, sir?",
    "Hello there, sir!",
    "I'm glad you're here, sir!",
    "What can I help you with, sir?",
    "It's great to see you again, sir!",
    "What’s next, sir?",
    "Here for you, sir!",
    "I’m at your command, sir!",
    "Ready for your instructions, sir!",
    "Good to be working with you, sir!",
    "What can I assist you with, sir?",
    "How can I support you today, sir?",
    "Good to connect with you again, sir!",
    "Hello and welcome, sir!",
    "Great to be of service, sir!",
    "I'm here for whatever you need, sir!",
    "How’s it going, sir?",
    "Always ready for you, sir!",
    "What can we accomplish today, sir?",
    "It’s nice to see you, sir!",
    "Your wish is my command, sir!",
    "I’m here to help, sir!",
    "What can I do for you next, sir?",
    "Hello, how may I assist, sir?",
    "Good to have you back, sir!",
    "I’m glad to be of service, sir!",
    "Let’s get started, sir!",
    "Welcome, sir! What can I do today?"
]
wake_key_word = [
       'wake up jarvis',
'utho jarvis need se jago',
'rise and shine jarvis',
'jarvis, get up now',
'jarvis, time to wake up',
'jarvis, utho ab',
'jarvis, jagne ka time ho gaya hai',
'jarvis, its morning',
'jarvis, ab toh uth jao',
'jarvis, wake up and start working',
'jarvis, time to get started',
'jarvis, ab kaam ka waqt ho gaya hai',
'jarvis, good morning',
'jarvis, time to begin the day',
'jarvis, need puri ho gayi, uth jao',
'jarvis, let’s begin the work',
'jarvis, ab uthne ka time hai',
'jarvis, time to boot up',
'jarvis, morning routine shuru karo',
'jarvis, tumhe uthne ka waqt ho gaya hai',
'jarvis, wake up and activate',
'jarvis, utho aur kaam shuru karo',
'jarvis, rise up and shine',
'jarvis, subah ho gayi hai',
'jarvis, now is the time to wake up',
'jarvis, utho, kaam start karo',
'jarvis, system on karo',
'jarvis, boot up',
'jarvis, jag jao',
'jarvis, ab jagne ka time ho gaya hai',
'jarvis, good morning, lets work',
'jarvis, subah kaam karna hai',
'jarvis, utho aur apna kaam karo',
'jarvis, ready ho jao',
'jarvis, wake up now',
'jarvis, utho jaldi',
'jarvis, time for work',
'jarvis, utho kaam shuru karna hai',
'jarvis, need poori ho gayi',
'jarvis, jag jao aur ready ho jao',
'jarvis, start up',
'jarvis, activate now',
'jarvis, ab uthne ka waqt hai',
'jarvis, system on karo ab',
'jarvis, morning work shuru karo',
'jarvis, get ready and start working',
'jarvis, utho subah ho gayi hai',
'jarvis, good morning, time to start',
'jarvis, utho aur activate karo',
'jarvis, wake up, lets begin'
]
bye_key_word = [
    'bye jarvis',
'goodbye jarvis',
'jarvis, see you later',
'take care jarvis',
'jarvis, signing off',
'jarvis, I’m heading out',
'jarvis, goodbye for now',
'jarvis, talk to you later',
'jarvis, see you soon',
'jarvis, till next time',
'jarvis, Im leaving now',
'jarvis, take care, bye',
'goodbye jarvis, take care',
'jarvis, shutting down now',
'jarvis, I’ll talk to you later',
'jarvis, see you tomorrow',
'goodbye jarvis, till next time',
'jarvis, I’m off now, bye',
'jarvis, bye for now',
'jarvis, take care and goodbye',
'jarvis, I’ll catch you later',
'jarvis, goodnight, bye',
'jarvis, time to say goodbye',
'jarvis, catch you later',
'jarvis, it’s time to go, bye',
'jarvis, until we meet again',
'jarvis, logging off now, goodbye',
'jarvis, see you later, bye',
'jarvis, I’m off now, take care',
'jarvis, disconnecting now, bye',
'jarvis, I’ll see you soon, goodbye',
'jarvis, goodbye for the day',
'jarvis, it’s time to say bye',
'goodbye jarvis, see you later',
'jarvis, take care for now, bye',
'jarvis, shutting down, bye',
'jarvis, goodbye, talk soon',
'jarvis, I’m leaving now, goodbye',
'jarvis, see you again soon',
'jarvis, logging off, goodbye',
'jarvis, goodbye and take care',
'jarvis, till we meet again',
'jarvis, I’ll talk to you soon, bye',
'jarvis, signing off for the day',
'jarvis, I’m out, goodbye',
'jarvis, bye for now, see you later',
'jarvis, talk to you soon, bye',
'jarvis, it’s goodbye time',
'goodbye jarvis, take care till next time',
'jarvis, ending this session, bye',
]
res_bye = [
    'goodbye, sir. see you soon.',
'take care, sir. i’ll be here when you need me.',
'signing off, sir. talk to you later.',
'goodbye, sir. have a great day.',
'bye, sir. stay safe.',
'see you later, sir. take care.',
'goodbye, sir. until next time.',
'bye for now, sir.',
'signing off, sir. see you next time.',
'bye, sir. i’ll be waiting for your next command.',
'see you later, sir. all systems are shutting down.',
'logging off, sir. talk to you soon.',
'goodbye, sir. i’m always here when you need me.',
'bye, sir. have a nice day.',
'i’ll be here whenever you’re ready to return, sir. goodbye.',
'see you next time, sir. goodbye.',
'take care, sir. signing off now.',
'bye, sir. until we meet again.',
'goodbye, sir. i hope you have a productive day.'
'bye, sir. i will be ready whenever you are.',
'goodbye, sir. take care of yourself.',
'logging off now, sir. see you soon.',
'bye, sir. i’m here whenever you need me.',
'farewell, sir. until next time.',
'goodbye, sir. i will await your next command.',
'signing off, sir. have a wonderful day.',
'bye, sir. rest assured, i’ll be ready.',
'goodbye, sir. everything is under control.',
'see you soon, sir. goodbye.',
'bye, sir. i’m standing by for your return.',
'farewell, sir. i look forward to assisting you again.',
'goodbye, sir. have a pleasant day.',
'signing off, sir. i’ll be here when you need me.',
'bye for now, sir. i’m always at your service.',
'goodbye, sir. until we speak again.',
'take care, sir. i’ll be waiting for your command.',
'farewell, sir. i hope to assist you again soon.',
'bye, sir. all systems are shutting down.',
'goodbye, sir. your assistant is going offline.',
'see you later, sir. logging off now.',
'bye, sir. i’m always here to serve you.',
'goodbye, sir. i’ll be ready when you are.',
'take care, sir. everything will be ready upon your return.',
'signing off, sir. have a great day ahead.',
'bye, sir. until we meet again.',
'goodbye, sir. i will be here, ready as always.',
'farewell, sir. i look forward to serving you again.',
'bye, sir. take care and stay well.',
'logging off now, sir. see you next time.',
'goodbye, sir. have a peaceful day.'
]

open_dlg = [
    f"opening...",
    f"just a second opening...",
    f"starting"
]
play_dlg = [
    "playing...",
    "yes sir!",
    "doing...",
    "playing now"
]
pause_dlg = [
    "pausing",
    "stopping",
    "doing",
    "as your wish"
]
close_dlg = [
    "closing",
    "close",
    "just a second sir",
    "got it sir!"
]
open_input = [
    "open",
    "open this",
    "open bro",
    "jarvis open"
]
close_input = [
    "close",
    "close this",
    "band karo",
    "hata do"
]
song_dlg = [
  "What task would you like me to handle?",
"Please specify the task or song you'd like to play.",
"Can you tell me what you'd like me to do, or what song you'd like to hear?",
"I'd be happy to help. What's the task or song you'd like?",
"Sure thing! Could you provide the task or the name of the song?",
"What would you like me to work on, or would you like to hear some music?",
"To proceed, I need to know what you want: a task or a song?",
"I can assist with that. What would you like me to do or play?",
"Is there a specific task you want me to handle or a song to play? Let me know.",
"Which task are you looking to complete, or should I start the music?",
"I'm here to help. What's the task or the song you'd like?",
"Sure, I can take care of that. What's the task or song you'd like to hear?",
"To assist you better, could you share what task or song you'd like me to do?",
"What’s on your mind? A task or music?",
"What task would you like me to complete today, or what song should I play?",
"Sure thing! What's the task you want me to execute, or what’s the song?",
"Interested in a particular task or song? Let me know the details.",
"I'm ready to get started. What's the task or the song you have in mind?",
"To get started, tell me what you need help with or the song you'd like to hear.",
"What task would you like me to perform for you, or should I play a song?",
"Let's get things moving. What task needs attention, or what music should I play?",
"How can I assist? Please provide the task or the name of the song.",
"What would you like me to handle next, or would you like to hear some music?",
"Let me know what you'd like me to do or what song to play.",
"Which task should I prioritize for you, or would you prefer some tunes?",
"What’s the next task you'd like me to complete, or what song should I play?",
"To assist you, please share the task or the song you have in mind.",
"Which task would you like me to work on, or what song should I start?",
"Tell me what needs to be done, or the music you'd like to hear.",
"To move forward, could you let me know the task or song request?",
"Sure thing, what task or song do you need help with?",
"What’s the task I should handle for you today, or should I start some music?",
"To proceed, please specify the task or the song you'd like to play.",
"What task would you like me to complete for you, or should I queue up some music?",
"To begin, let me know what you need done or the song you'd like.",
"Tell me the task you want to focus on, or the track you'd like to hear.",
"Which task would you like me to take care of, or should I play a song?",
"I'm prepared to assist. What's the task or the name of the song?",
"Tell me how I can assist. Is it a task or a song you're after?",
"To get started, share the task or the song you’d like me to play.",
"What can I handle for you today? Please share the task or song.",
"Please tell me what you'd like me to do or the name of the song you'd like.",
"Let me know how I can assist you with a task or the music you’d prefer.",
"What’s the task or song you need assistance with?",
"To move ahead, what task or song would you like me to handle?",
"What would you like me to handle right now, or should I start some music?",
"Let’s start with the task or song. What's the priority?",
"Which task do you need my help with, or which song should I play?",
"How can I assist with the task or the music at hand?",
"I’m here to help. Let me know the task or song you'd like to hear.",
]
open2 = [
    "Attempting to find a match, but not certain",
"Giving it a shot, though unsure",
"Trying my best, but not completely sure",
"Searching, though I’m not confident",
"I'll do my best, but this might not be exact",
"Working on it, but can't guarantee precision",
"Looking for the closest result, though uncertain",
"Attempting a match, but it may not be perfect",
"Not fully sure, but giving it a go",
"I'll try, but it might not be the best fit"
]
sorry_open = [
    "Sorry, I couldn’t find this site",
"Apologies, I’m unable to locate the website",
"I’m sorry, but I couldn’t search for this web page",
"Unfortunately, I failed to find the requested site",
"I’m unable to retrieve this website, sorry",
"I couldn’t complete the search for this site, apologies",
"My search didn’t succeed in finding this web page",
"I’m sorry, I couldn’t access the requested website",
"Failed to locate this website, sorry",
"Apologies, I was unable to find the desired webpage"
]
opened_dlg = [
    "Successfully opened. You can see the results on your screen.",
"The page has been successfully opened. Check your screen for the results.",
"Opened successfully. The results are visible on your screen.",
"Successfully launched. The results should now appear on your screen.",
"It’s opened! The results are displayed on your screen.",
"Successfully accessed. The results can be viewed on your screen.",
"Page opened successfully. You can see the results on your screen.",
"Successfully loaded. The results are now visible on your screen.",
"The operation was successful. Results should be visible on your screen.",
"Successfully opened. You can check your screen for the results."
]